config/routes.rb
Rails.application.routes.draw do
  resources :drugs
  resources :meds
  devise_for :admins
  resources :appointments
  devise_for :users
  get 'home/index'
  get '/aboutus' => 'home#aboutus'
  get '/users' => 'users#index'

  resources :doctors do
  resources:appointments
end

  resources :patients do
    resources:appointments
  end

   root 'home#index'
   
  controller :patients do
  get 'patients/show'     => :show
  get 'patients/delete'   => :new
  get 'patients/edit/:id' => :edit
  get 'patients/delete'   => :index
  post 'patients/show'     => :show
  post 'patients/delete'   => :new
  post 'patients/edit/:id' => :edit
  post 'patients/delete'   => :index
end

controller :users do
  get 'users'     => :show
  get 'users/delete'   => :new
  get 'users/edit/:id' => :edit
  get 'users/delete'   => :index
  get 'users/edit'=> :edit
   put 'users/edit'=> :edit
  post 'users/show'     => :show
  post 'users/delete'   => :new
  post 'users/edit/:id' => :edit
  post 'users/delete'   => :index
  get 'profile' => :show
end

controller :doctors do
  get 'doctors/show'     => :show
  get 'doctors/delete'   => :new
  get 'doctors/edit/:id' => :edit
  get 'doctors/delete'   => :index
  post 'doctors/show'     => :show
  post 'doctors/delete'   => :new
  post 'doctors/edit/:id' => :edit
  post 'doctors/delete'   => :index
  get 'doctors_list' => :doctors_list
  
end
controller :appointments do
  get 'appointments/show'     => :show
  get 'appointments/delete'   => :new
  get 'appointments/edit/:id' => :edit
  get 'appointments/delete'   => :index
  post 'appointments/show'     => :show
  post 'appointments/delete'   => :new
  post 'appointments/edit/:id' => :edit
  post 'appointments/delete'   => :index
end

end

app/models/drug.rb
class Drug < ActiveRecord::Base
  def self.search(search)
    if search
      if Rails.env.development?
        where("firstname LIKE ?", "%#{search}%")
      elsif Rails.env.production?
        where("firstname ILIKE ?", "%#{search}%")
      end
    else
      all
    end
  end
end

app/controllers/drugs_controller.rb
class DrugsController < ApplicationController
  require 'drug_decorator'
  before_action :set_drug, only: [:show, :edit, :update, :destroy]

  # GET /drugs
  # GET /drugs.json
def index
  @drugs = Drug.all
  if params[:search]
    @drugs = Drug.search(params[:search]).order("created_at DESC")
  else
    @drugs = Drug.all.order('created_at DESC')
  end
end

  # GET /drugs/1
  # GET /drugs/1.json
  def show
  end

  # GET /drugs/new
  def new
    @drug = Drug.new
  end

  # GET /drugs/1/edit
  def edit
  end

  # POST /drugs
  # POST /drugs.json
def create
@drug = Drug.new()
@drug.firstname = params[:drug][:firstname]
@drug.lastname = params[:drug][:lastname]
@drug.age = params[:drug][:age]
@drug.firm = params[:drug][:firm]
# create an instance/object of a BasicDrug
myDrug = BasicDrug.new(2, @drug.firm, @drug.age)
# add the extra features to the new drug
if params[:drug][:windows].to_s.length > 0 then
myDrug = ElectricWindowsDecorator.new(myDrug)
end

if params[:drug][:panadols].to_s.length > 0 then
myDrug = PanadolsDecorator.new(myDrug)
end

## populate the cost and the description details
@drug.cost = myDrug.cost
@drug.description = myDrug.details
respond_to do |format|
if @drug.save
format.html { redirect_to @drug, notice: 'Order placed for drug successfully.'}
format.json { render :show, status: :created, location: @drug }
else
format.html { render :new }
format.json { render json: @drug.errors, status: :unprocessable_entity }
end
end
end
  # PATCH/PUT /drugs/1
  # PATCH/PUT /drugs/1.json
  def update
    respond_to do |format|
      if @drug.update(drug_params)
        format.html { redirect_to @drug, notice: 'Drug was successfully updated.' }
        format.json { render :show, status: :ok, location: @drug }
      else
        format.html { render :edit }
        format.json { render json: @drug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drugs/1
  # DELETE /drugs/1.json
  def destroy
    @drug.destroy
    respond_to do |format|
      format.html { redirect_to drugs_url, notice: 'Drug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drug
      @drug = Drug.find(params[:id])
    end

    # Never trust parameters from the sdrugy internet, only allow the white list through.
    def drug_params
      params.require(:drug).permit(:firstname, :lastname, :firm, :cost, :description, :age)
    end
end

app/helpers/drugs_helper.rb
module DrugsHelper
end

app/views/drugs/_form.html.erb
<%= form_for(@drug) do |f| %>
  <% if @drug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@drug.errors.count, "error") %> prohibited this drug from being saved:</h2>

      <ul>
      <% @drug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :firm %><br>
    <%= f.text_field :firm %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  
  
  <div class="field">
Biotene:
<%= check_box_tag 'drug[windows]', 'windows' %>
</div>
  
  <div class="field">
Panadol:
<%= check_box_tag 'drug[panadols]', 'panadols' %>
</div>  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drugs/edit.html.erb
<h1>Editing Drug</h1>

<%= render 'form' %>

<%= link_to 'Show', @drug %> |
<%= link_to 'Back', drugs_path %>

app/views/drugs/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag(drugs_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search by firstname" %>
<%= submit_tag "Search" %>
<% end %>

<h1>Listing Drugs</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Firm</th>
      <th>Cost</th>
      <th>Description</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drugs.each do |drug| %>
      <tr>
        <td><%= drug.firstname %></td>
        <td><%= drug.lastname %></td>
        <td><%= drug.firm %></td>
        <td><%= drug.cost %></td>
        <td><%= drug.description %></td>
        <td><%= drug.age %></td>
        <td><%= link_to 'Show', drug %></td>
        <td><%= link_to 'Edit', edit_drug_path(drug) %></td>
        <td><%= link_to 'Destroy', drug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Drug', new_drug_path %>

app/views/drugs/new.html.erb
<h1>New Drug</h1>

<%= render 'form' %>

<%= link_to 'Back', drugs_path %>

app/views/drugs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @drug.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @drug.lastname %>
</p>

<p>
  <strong>Firm:</strong>
  <%= @drug.firm %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @drug.cost %>
</p>



<p>
  <strong>Age:</strong>
  <%= @drug.age %>
</p>

<%= link_to 'Edit', edit_drug_path(@drug) %> |
<%= link_to 'Back', drugs_path %>