config/routes.rb
Rails.application.routes.draw do
  resources :drugs
  resources :meds
  devise_for :admins
  resources :appointments
  devise_for :users
  get 'home/index'
  get '/aboutus' => 'home#aboutus'
  get '/users' => 'users#index'

  resources :doctors do
  resources:appointments
end

  resources :patients do
    resources:appointments
  end

   root 'home#index'
   
  controller :patients do
  get 'patients/show'     => :show
  get 'patients/delete'   => :new
  get 'patients/edit/:id' => :edit
  get 'patients/delete'   => :index
  post 'patients/show'     => :show
  post 'patients/delete'   => :new
  post 'patients/edit/:id' => :edit
  post 'patients/delete'   => :index
end

controller :users do
  get 'users'     => :show
  get 'users/delete'   => :new
  get 'users/edit/:id' => :edit
  get 'users/delete'   => :index
  get 'users/edit'=> :edit
   put 'users/edit'=> :edit
  post 'users/show'     => :show
  post 'users/delete'   => :new
  post 'users/edit/:id' => :edit
  post 'users/delete'   => :index
  get 'profile' => :show
end

controller :doctors do
  get 'doctors/show'     => :show
  get 'doctors/delete'   => :new
  get 'doctors/edit/:id' => :edit
  get 'doctors/delete'   => :index
  post 'doctors/show'     => :show
  post 'doctors/delete'   => :new
  post 'doctors/edit/:id' => :edit
  post 'doctors/delete'   => :index
  get 'doctors_list' => :doctors_list
  
end
controller :appointments do
  get 'appointments/show'     => :show
  get 'appointments/delete'   => :new
  get 'appointments/edit/:id' => :edit
  get 'appointments/delete'   => :index
  post 'appointments/show'     => :show
  post 'appointments/delete'   => :new
  post 'appointments/edit/:id' => :edit
  post 'appointments/delete'   => :index
end

end

app/models/med.rb
class Med < ActiveRecord::Base
    
  def self.search(search)
    if search
      if Rails.env.development?
        where("firstname LIKE ?", "%#{search}%")
      elsif Rails.env.production?
        where("firstname ILIKE ?", "%#{search}%")
      end
    else
      all
    end
  end
end

app/controllers/meds_controller.rb
class MedsController < ApplicationController
  require 'med_decorator'
  before_action :set_med, only: [:show, :edit, :update, :destroy]

  # GET /meds
  # GET /meds.json
  def index
    @meds = Med.all
    @meds = Med.search(params[:search])
  end

  # GET /meds/1
  # GET /meds/1.json
  def show
  end

  # GET /meds/new
  def new
    @med = Med.new
  end

  # GET /meds/1/edit
  def edit
  end

  # POST /meds
  # POST /meds.json
def create
@med = Med.new()
@med.firstname = params[:med][:firstname]
@med.lastname = params[:med][:lastname]
@med.cost = params[:med][:cost]
# create an instance/object of a BasicMed
myMed = BasicMed.new(15, @med.firstname, @med.lastname)
# add the extra features to the new med
if params[:med][:windows].to_s.length > 0 then
myMed = ElectricWindowsDecorator.new(myMed)
end

## populate the cost and the description details
@med.cost = myMed.cost
@med.description = myMed.details
respond_to do |format|
if @med.save
format.html { redirect_to @med, notice: 'Med was successfully created.'}
format.json { render :show, status: :created, location: @med }
else
format.html { render :new }
format.json { render json: @med.errors, status: :unprocessable_entity }
end
end
end
  # PATCH/PUT /meds/1
  # PATCH/PUT /meds/1.json
  def update
    respond_to do |format|
      if @med.update(med_params)
        format.html { redirect_to @med, notice: 'Med was successfully updated.' }
        format.json { render :show, status: :ok, location: @med }
      else
        format.html { render :edit }
        format.json { render json: @med.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meds/1
  # DELETE /meds/1.json
  def destroy
    @med.destroy
    respond_to do |format|
      format.html { redirect_to meds_url, notice: 'Med was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_med
      @med = Med.find(params[:id])
    end

    # Never trust parameters from the smedy internet, only allow the white list through.
    def med_params
      params.require(:med).permit(:firstname, :lastname, :cost)
    end
end

app/helpers/meds_helper.rb
module MedsHelper
end

app/views/meds/_form.html.erb
<%= form_for(@med) do |f| %>
  <% if @med.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@med.errors.count, "error") %> prohibited this med from being saved:</h2>

      <ul>
      <% @med.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  
  
  <div class="field">
Electric windows:
<%= check_box_tag 'med[windows]', 'windows' %>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meds/edit.html.erb
<h1>Editing Med</h1>

<%= render 'form' %>

<%= link_to 'Show', @med %> |
<%= link_to 'Back', meds_path %>

app/views/meds/index.html.erb
<p id="notice"><%= notice %></p>


<%= form_tag meds_path, method: :get do %>
<p>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag 'Search', name: nil %>
</p>
<% end %>

<h1>Listing Meds</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meds.each do |med| %>
      <tr>
        <td><%= med.firstname %></td>
        <td><%= med.lastname %></td>
        <td><%= med.cost %></td>
        <td><%= link_to 'Show', med %></td>
        <td><%= link_to 'Edit', edit_med_path(med) %></td>
        <td><%= link_to 'Destroy', med, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Med', new_med_path %>

app/views/meds/new.html.erb
<h1>New Med</h1>

<%= render 'form' %>

<%= link_to 'Back', meds_path %>

app/views/meds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @med.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @med.lastname %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @med.cost %>
</p>

<%= link_to 'Edit', edit_med_path(@med) %> |
<%= link_to 'Back', meds_path %>