config/routes.rb
Rails.application.routes.draw do
  resources :drugs
  resources :meds
  devise_for :admins
  resources :appointments
  devise_for :users
  get 'home/index'
  get '/aboutus' => 'home#aboutus'
  get '/users' => 'users#index'

  resources :doctors do
  resources:appointments
end

  resources :patients do
    resources:appointments
  end

   root 'home#index'
   
  controller :patients do
  get 'patients/show'     => :show
  get 'patients/delete'   => :new
  get 'patients/edit/:id' => :edit
  get 'patients/delete'   => :index
  post 'patients/show'     => :show
  post 'patients/delete'   => :new
  post 'patients/edit/:id' => :edit
  post 'patients/delete'   => :index
end

controller :users do
  get 'users'     => :show
  get 'users/delete'   => :new
  get 'users/edit/:id' => :edit
  get 'users/delete'   => :index
  get 'users/edit'=> :edit
   put 'users/edit'=> :edit
  post 'users/show'     => :show
  post 'users/delete'   => :new
  post 'users/edit/:id' => :edit
  post 'users/delete'   => :index
  get 'profile' => :show
end

controller :doctors do
  get 'doctors/show'     => :show
  get 'doctors/delete'   => :new
  get 'doctors/edit/:id' => :edit
  get 'doctors/delete'   => :index
  post 'doctors/show'     => :show
  post 'doctors/delete'   => :new
  post 'doctors/edit/:id' => :edit
  post 'doctors/delete'   => :index
  get 'doctors_list' => :doctors_list
  
end
controller :appointments do
  get 'appointments/show'     => :show
  get 'appointments/delete'   => :new
  get 'appointments/edit/:id' => :edit
  get 'appointments/delete'   => :index
  post 'appointments/show'     => :show
  post 'appointments/delete'   => :new
  post 'appointments/edit/:id' => :edit
  post 'appointments/delete'   => :index
end

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
    #attr_accessible :name
    has_many :appointments
  has_many :patients, through: :appointments
    after_create :send_welcome_email
    
    def send_welcome_email
      puts "Hello Doctor Welcome to the Panel"
       WelcomeMail.welcome_email(self).deliver_now
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_filter :set_doctor, only: [:show, :edit, :update, :destroy]
 #before_filter :authenticate_user!
 #validates :dname, presence: true
 #validates :email, presence: true
 # validates :contact, length: { is: 10}
  #validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  # GET /doctors
  # GET /doctors.json
  def index
    
    @doctors = Doctor.all
  end

  def doctors_list
  
    
    @doctors = Doctor.all
  end
  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
   #  before_filter :authenticate_user, :only => [:account_settings, :set_account_info]
    @doctor = Doctor.new
  end
    def content
      @doctor= Doctor.paginate(:page => params[:page], :per_page => 12)
      respond_to do |format|
        format.html # content.html.erb
      end
    end  
  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
   # @doctor = Doctor.new(doctor_params)
   @doctor = Doctor.new()
        @doctor.dname = params[:doctor][:dname]
@doctor.email = params[:doctor][:email]
@doctor.default_appoinment_duration = params[:doctor][:default_appoinment_duration]
@doctor.speciality = params[:doctor][:speciality]
@doctor.contact = params[:doctor][:contact]

    respond_to do |format|
      if @doctor.save
     # generated_password = Devise.friendly_token.first(8)
        @password=@doctor.contact
       # logger = Logger.new("password"+@password)
       # puts "password"+@password
        
        User.create!({:email => @doctor.email, :role => "doctor", :password => @password, :password_confirmation => @password })
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
         
        format.json { render :show, status: :created, location: @doctor }
         WelcomeMail.welcome_email(@user).deliver
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:dname, :email, :default_appoinment_duration,:speciality)
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= form_for(@doctor) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dname %><br>
    <%= f.text_field :dname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :default_appoinment_duration %><br>
    <%= f.number_field :default_appoinment_duration %>
  </div>
  <div class="field">
    <%= f.label :speciality %><br>
    <%= f.text_field :speciality %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :contact %>
  </div>
  <!--div class="field"-->
    <!--%= f.label :NPI %><br-->
    <!--%= f.text_field :NPI %-->
  <!--/div-->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doctors/doctors_list.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Doctors</h1>

<table>
  <thead>
    <tr>
      <th>Dname</th>
      <th>Email</th>
      <th>Default appoinment duration</th>
      <th>Speciality</th>
       <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   
     
    <!--%if( current_user&& (current_user.try(:admin?))%-->
      <% @doctors.each do |doctor| %>
        <tr>
          <td><%= doctor.dname %></td>
          <td><%= doctor.email %></td>
          <td><%= doctor.default_appoinment_duration %></td>
          <td><%= doctor.speciality %></td>
          <%if( current_user&& (current_user.try(:admin?)))%>
          
           <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
           <td><%= link_to 'Edit', edit_doctor_path(doctor) %> </td>
          <%end%>
           
           
          
          <!--%if(doctor.active==true)%>
            <td><!--%= link_to 'Show Details', doctor %></td>
          <!--%else%>
            <td><!--%= link_to'Hide', doctor %></td>
          <!--% end %--><!--Activecheck if-->
           
          
        </tr>
      <%end%>        <!--doctors loop end-->
      
   
    
   

  </tbody>
</table>

<%if( current_user&& (current_user.try(:admin?)))%>
<%= link_to 'New Doctor', new_doctor_path %>
<%end%>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Doctors</h1>

<table>
  <thead>
    <tr>
      <th>Dname</th>
      <th>Email</th>
      <th>Default appoinment duration</th>
      
       <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if((user_signed_in?) && (current_user.role=="doctor"))%>
      <% @doctors.each do |doctor| %>
      <% if( (doctor.email==current_user.email))%>
        <tr>
          <td><%= doctor.dname %></td>
          <td><%= doctor.email %></td>
          <!---->
         
          <td><%= link_to 'Show Appointment', doctor_appointments_path(doctor) %></td>
         <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         
        </tr>
      <%end%><!---->
      <%end%>
    <%else%>
    <!--%if( current_user&& (current_user.try(:admin?))%-->
      <% @doctors.each do |doctor| %>
        <tr>
          <td><%= doctor.dname %></td>
          <td><%= doctor.email %></td>
          <td><%= doctor.default_appoinment_duration %></td>
          <%if( current_user&& (current_user.try(:admin?)))%>
          
           <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
           <td><%= link_to 'Edit', edit_doctor_path(doctor) %> </td>
          <%end%>
           <td><%= link_to 'Book Appointment', new_doctor_appointment_path(doctor) %></td>
           <td><%= link_to 'Show Appointment', doctor_appointments_path(doctor) %></td>
           
          
          <!--%if(doctor.active==true)%>
            <td><!--%= link_to 'Show Details', doctor %></td>
          <!--%else%>
            <td><!--%= link_to'Hide', doctor %></td>
          <!--% end %--><!--Activecheck if-->
           
          
        </tr>
      <%end%>        <!--doctors loop end-->
      
    <%end%>
    
   

  </tbody>
</table>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form' %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dname:</strong>
  <%= @doctor.dname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @doctor.email %>
</p>

<p>
  <strong>Default appoinment duration:</strong>
  <%= @doctor.default_appoinment_duration %>
</p>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>