config/routes.rb
Rails.application.routes.draw do
  resources :drugs
  resources :meds
  devise_for :admins
  resources :appointments
  devise_for :users
  get 'home/index'
  get '/aboutus' => 'home#aboutus'
  get '/users' => 'users#index'

  resources :doctors do
  resources:appointments
end

  resources :patients do
    resources:appointments
  end

   root 'home#index'
   
  controller :patients do
  get 'patients/show'     => :show
  get 'patients/delete'   => :new
  get 'patients/edit/:id' => :edit
  get 'patients/delete'   => :index
  post 'patients/show'     => :show
  post 'patients/delete'   => :new
  post 'patients/edit/:id' => :edit
  post 'patients/delete'   => :index
end

controller :users do
  get 'users'     => :show
  get 'users/delete'   => :new
  get 'users/edit/:id' => :edit
  get 'users/delete'   => :index
  get 'users/edit'=> :edit
   put 'users/edit'=> :edit
  post 'users/show'     => :show
  post 'users/delete'   => :new
  post 'users/edit/:id' => :edit
  post 'users/delete'   => :index
  get 'profile' => :show
end

controller :doctors do
  get 'doctors/show'     => :show
  get 'doctors/delete'   => :new
  get 'doctors/edit/:id' => :edit
  get 'doctors/delete'   => :index
  post 'doctors/show'     => :show
  post 'doctors/delete'   => :new
  post 'doctors/edit/:id' => :edit
  post 'doctors/delete'   => :index
  get 'doctors_list' => :doctors_list
  
end
controller :appointments do
  get 'appointments/show'     => :show
  get 'appointments/delete'   => :new
  get 'appointments/edit/:id' => :edit
  get 'appointments/delete'   => :index
  post 'appointments/show'     => :show
  post 'appointments/delete'   => :new
  post 'appointments/edit/:id' => :edit
  post 'appointments/delete'   => :index
end

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
 #attr_accessible :patient_id, :doctor_id
  belongs_to :patient
  belongs_to :doctor
  validates :appointmentdate, uniqueness: {scope: [:startTime,:doctor_id] , 
     message: ->(object, data) do
        "The slot is already taken"
      end
      
  }
  
 # validates :uniqueness_of_fields

#private # optionnal
#def uniqueness_of_fields
#  if self.class.exists?(start_time: self[:start_time], appointmentdate: self[:appointmentdate])
 #   self.errors.add(:start_time, "Combination #{self[:start_time]} and #{self[:appointmentdate]} already existings!")
   # logger :do_your_thing # here is where you want to log stuff
 #   return false
 # else
 #   return true # validation passes, is unique
 # end
#end
  
 before_create:isAvailable
  after_create :reminder
 
 def isAvailable
     @appointments_list = Appointment.all
    @appointments_list.each do |appointment|
      if((appointment.appointmentdate == 'self.appointmentdate') && (appointment.doctor_id== 'self.doctor_id')) 
         puts " Duration clash*** "
         raise "Duration clash *****"
      end
   end
 end
  
  @@REMINDER_TIME = 60.minutes # minutes before appointment

  # Notify our appointment attendee X minutes before the appointment time
  def reminder
    @twilio_number = ['0899836680']
    @number_to_send_to=['0894535936']
    twilio_sid = "AC739629072ce99fbefb492d1bed12e63d"
    twilio_token = "02d18d90c9e669843a2eb07ab3bd87bf"
   # @client = Twilio::REST::Client.new ENV['AC25d1eab9c54f98e27b49e76145798780'], ENV['a10f83dc36e85901005966cc2d8c7c81']
   # time_str = ((self.startTime).localtime).strftime("%I:%M%p on %b. %d, %Y")
   # reminder = "Hi . Just a reminder that you have an appointment coming up at #{time_str}."
   # message = @client.accounts.messages.create(
   #      :from => @twilio_number,
   #   :to => self.pnumber,
   #   :body => reminder,
   # )
    
    @twilio_client = Twilio::REST::Client.new twilio_sid, twilio_token
 time_str = ((self.startTime).localtime).strftime("%I:%M%p on %b. %d, %Y")
@twilio_client.messages.create(
  :from => "+353861801379",
  :to =>  "+353834882018",
  :body => "Hi . You have appointment at #{time_str}"
)

    #puts message.to
  end

  def when_to_run
    time - @@REMINDER_TIME
  end
 
 def self.search(search)
     where("self.comment LIKE ?", "%#{search}%")
  end
# handle_asynchronously :reminder, :run_at => Proc.new { |i| i.when_to_run }

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_filter :authenticate_user!
 # before_filter :isAvailable, :only => :create
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  
  #validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  # GET /appointments
  # GET /appointments.json
   def isAvailable
             redirect_to doctor_appointment_path(@doctor,@appointment)
   end
  
  def index
  #  @appointments = Appointment.all
     @doctor = Doctor.find(params[:doctor_id])
  #  @appointments = @doctor.appointments
    if params[:search]
        puts "in search"
        puts params[:search].inspect
        @criteria = params[:search]
        @appointments = @doctor.appointments.where(comment: @criteria)
    else
        @appointments = @doctor.appointments
      @appointment= Appointment.all.order('created_at DESC')
       puts "in search else"
    end
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
   @doctor = Doctor.find(params[:doctor_id])
   @appointment = @doctor.appointments.find(params[:id])
  end

  # GET /appointments/new
  def new
    # respond_to do |format|
 #  if(!self.isAvailable)
  @doctor = Doctor.find(params[:doctor_id])
  @appointment = @doctor.appointments.build
#end
    #@appointment = Appointment.new
  #  else
      #format.html { redirect_to @appointment, notice: 'Appointment was successfully_created.' }
       # format.json { render :show, status: :created, location: @appointment }
       #  format.html { render :new }
        #  format.json { render json: @appointment.errors, status: :unprocessable_entity }
   # end
  end

  # GET /appointments/1/edit
  def edit
    @doctor = Doctor.find(params[:doctor_id])
# For URL like /movies/1/reviews/2/edit
# Get review id=2 for movie 1
@appointment = @doctor.appointments.find(params[:id])
  end

  # POST /appointments
  # POST /appointments.json
  def create
   #@doctor = Doctor.find(params[:doctor_id])
  # @appointment = @doctor.appointments.build(params.require(:appointment).permit(:startTime, :comment, :patient_id, :doctor_id))
   # @appointment = Appointment.new(appointment_params)
   #@appointment.startTime = params[:appointment][:startTime]
   #@appointment.comment = params[:appointment][:comment]
  #  @appointment.patient_id = params[:appointment][:patient_id]
   #@doctor_id1 = params[:appointment][:doctor_id]
  #@appointment.appointmentdate = params[:appointment][:appointmentdate]
    @doctor = Doctor.find(params[:doctor_id])
   @appointment = @doctor.appointments.build(params.require(:appointment).permit(:appointmentdate, :startTime, :comment, :patient_id, :doctor_id))
     #respond_to do |format|
      #  @appointments_list = Appointment.all
      
      @appointment.patientname=current_user.email
        
        
      if @appointment.save
       # format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        #format.json { render :show, status: :created, location: @appointment }
        redirect_to doctor_appointment_path(@doctor, @appointment)
      else
   
        # format.html { render :isAvailable }
        render 'new'
      end
        
                                          
  end
  


  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    @doctor = Doctor.find(params[:doctor_id])
    @appointment = Appointment.find(params[:id])
    
   if @appointment.update_attributes(params.require(:appointment).permit(:appointmentdate, :startTime, :comment, :patient_id, :doctor_id))
    # Save the review successfully
    redirect_to doctor_appointment_path(@doctor, @appointment)
   else  
      render :action => "edit"
   end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
  #@doctor = Doctor.find(params[:doctor_id])
   @appointment = Appointment.find(params[:id])
   @appointment.destroy
   respond_to do |format|
    format.html { redirect_to doctors_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
 
    
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      #@appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:appointmentdate, :startTime, :comment, :patient_id, :doctor_id)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper

end

app/views/appointments/_form.html.erb
<%= form_for([@doctor, @appointment]) do |f| %>
<form onsubmit= @appointment.isAvailable >
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :appointmentdate %><br>
    <%= f.date_select :appointmentdate %>
  </div>
  <!--%start_time = Time.parse("9 AM").to_i
start_interval = Time.parse("11 AM").to_i
end_interval = Time.parse("1 PM").to_i
end_time = Time.parse("6 PM").to_i
values = (start_time..end_time).step(15.minutes).select{|t| t <= start_interval || t >= end_interval }
  %-->
  
  <div class="field">
    <%= f.label :startTime %><br>
    <%= f.time_select :startTime %>
  </div>
  
  <div class="field">
    <%= f.label "Description" %><br>
    <%= f.text_field :comment %>
  </div>
 
 <div class="field">
    <%= f.label "Contact Number to get the reminder" %>
    <%= f.text_field :pnumber %>
    </div>
    
    
 
  
 <!--div class="field"-->
    <!--%= f.label "Enter Doctor name::(refer the details given below)"%-->
    <!--%= f.text_field :doctor_id %-->
    
  <!--/div-->
  
 
<!--  Enter your phone number ::(get notified through our SMS service)
  <div class="field">
    <!--%= f.text_field :phone %-->
    
  <!--/div-->
  
  
  <!--/div-->
  <div class="actions">
    <!--%=f.doctor_id= :doctor_id%-->
      <%= f.submit %>
  </div>
</form>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', doctor_appointment_path(@doctor,@appointment) %> 

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>
<%= form_tag(doctor_appointments_path(@doctor), :method => "get") do %>
<%= text_field_tag :search, nil, :placeholder => "Search Appointment by Description" %>
<%= submit_tag "Search" %>
<% end %>
<h1>Listing Appointments</h1>


<table>
  <thead>
    <tr>
      <th>Appointmentdate</th>
      <th>Starttime</th>
      <th>Reason for Appointment</th>
      <th>Doctor</th>
      <th>Patient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
    <% if( (appointment.patientname==current_user.email))%>
      <tr>
        <td><%= appointment.appointmentdate %></td>
        <td><%= appointment.startTime %></td>
        <td><%= appointment.comment %></td>
        <td><%= appointment.doctor_id %></td>
        <td><%= appointment.patientname %></td>
        <td><%= link_to 'Show', doctor_appointment_path(@doctor, appointment) %></td>
        <td><%= link_to 'Reschedule', edit_doctor_appointment_path(@doctor, appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <%end%>
    <%else%>
     <% @appointments.each do |appointment| %>
      <%if( current_user&& ((current_user.try(:admin?))||(current_user.role=="doctor")))%>
     <td><%= appointment.appointmentdate %></td>
        <td><%= appointment.startTime %></td>
        <td><%= appointment.comment %></td>
        <td><%= appointment.doctor_id %></td>
        <td><%= appointment.patientname %></td>
        <td><%= link_to 'Show', doctor_appointment_path(@doctor, appointment) %></td>
        <td><%= link_to 'Reschedule', edit_doctor_appointment_path(@doctor, appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
     <%end%>
  </tbody>
</table>

<br>


<%= link_to 'New Appointment', doctors_path %>

 
   
 
 
  
    

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Appointmentdate:</strong>
  <%= @appointment.appointmentdate %>
</p>

<p>
  <strong>Startime:</strong>
  <%= @appointment.startTime %>
</p>


  <strong>Description</strong>
  <%= @appointment.comment %>
</p>



<p>
  <strong>Doctor:</strong>
  <%= @appointment.doctor.dname %>
</p>

<p>
  <strong>Patient Email:</strong>
  <%= @appointment.patientname %>
</p>





<%= link_to 'Edit', edit_doctor_appointment_path(@doctor, @appointment) %> |
<%= link_to 'Book another appointment for same doctor', new_doctor_appointment_path(@doctor) %>